[build]
target = "x86_64-unknown-none"

[target.x86_64-unknown-none]
linker = "ld.lld"

rustflags = [
    "-C", "relocation-model=static",
    "-C", "link-arg=-Tlinker-x86_64.ld",
    "-C", "link-arg=-no-pie",
    "-C", "link-arg=-static",
    "-C", "link-arg=-nostdlib",
]
